---
pre-built-executables:
    type: zip
    link: https://microchiptechnology-my.sharepoint.com/:u:/g/personal/hugh_breslin_microchip_com/EYyolGZ8WHdLvTVFi5EZmgoBpSTRTRuHXPk4GWRvYbl3GA?e=6MXSai&download=1
HSS:
    type: git
    link: https://github.com/polarfire-soc/hart-software-services.git
    branch: master
    commit: 63a8eee608d
HSS-payload-generator:
    type: zip
    link: https://github.com/polarfire-soc/hart-software-services/releases/download/2021.11/hss-payload-generator.zip
HDL:
    type: git
    link: https://github.com/polarfire-soc/icicle-kit-minimal-bring-up-design-hdl-src.git
    branch: main
    commit: 9e966085bab
bare-metal-examples:
    type: git
    link: https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples.git
    branch: main
    commit: acdddf3

# Source format:
# - [NAME]:
#     type: [type]
#     link: [link]
#     branch: [name] # if using git as a type
#     commit: [hash] # if using git, you can checkout a specific commit on a branch

