---
pre-built-executables:
    type: zip
    link: https://microchiptechnology-my.sharepoint.com/:u:/g/personal/hugh_breslin_microchip_com/ETsITxrZtTxMm_cegzsk5aMB04jVvet-iHExmzI9fZn-Ng?e=tLGDUq&download=1
HSS:
    type: git
    link: https://bitbucket.microchip.com/scm/fpga_pfsoc_es/hart-software-services.git
    branch: develop
    commit: dce6f1ae751
HSS-payload-generator:
    type: zip
    link: https://github.com/polarfire-soc/hart-software-services/releases/latest/download/hss-payload-generator.zip
HDL:
    type: git
    link: https://bitbucket.microchip.com/scm/fpga_pfsoc_es/icicle-kit-minimal-bring-up-design-src.git
    branch: initial-work
bare-metal-examples:
    type: git
    link: https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples.git
    branch: main

# Source format:
# - [NAME]:
#     type: [type]
#     link: [link]
#     branch: [name] # if using git as a type
#     commit: [hash] # if using git, you can checkout a specific commit on a branch

